export const SAAS_LIMITS = {
  FREE: {
    PLATFORMS: 2,
    PLANS: 6,
    ACTIVE_SEATS: 12,
    CLIENTS: 50,
    SUBSCRIPTIONS: 6,
  },
  PREMIUM: {
    PLATFORMS: Number.MAX_SAFE_INTEGER,
    PLANS: Number.MAX_SAFE_INTEGER,
    ACTIVE_SEATS: Number.MAX_SAFE_INTEGER,
    CLIENTS: Number.MAX_SAFE_INTEGER,
    SUBSCRIPTIONS: Number.MAX_SAFE_INTEGER,
  },
} as const;
